---
title: "Brother, Can You Spare a Manufacturing Job?  How Voters React to Deindustrialization"
author:
- affiliation: Harvard University
  email: cdarin@hks.harvard.edu
  firstname: Catherine
  name: Catherine Darin
  surname: Darin
- affiliation: Harvard University
  email: zagrebmukerjee@fas.harvard.edu
  firstname: Zagreb
  name: Zagreb Mukerjee
  surname: Mukergee
acknowledgements: null
output:
  pdf_document: default
  rticles::aea_article: default
jel:
- ~
- ~
journal: ''
keywords:
- ~
- ~
month: `r format(Sys.Date(), '%m')`
issue: 1
short: ''
abstract: |
  What led to Donald Trump's surprising 2016 election victory? This paper examines the potential contribution of deindustrialization. Counties differ by exposure to manufacturing, which we use in an instrumental-variable approach to identify the effect of manufacturing job loss on change in Democratic vote share. We find that Democratic vote share falls in counties with high manufacturing job loss since 2004. Disaggregating this result by race shows that the Democratic vote share fell where layoffs affected white populations, and rose where layoffs affected nonwhites. This suggests a racial component to how voters process economic hardship.
vol: 1
year: `r format(Sys.Date(), '%Y')`
---

\section{Introduction}

We replicate Baccini and Wemouth (2021), which analyzes the effect of gross manufacturing job losses from 2012 to 2015 on the change in Democratic vote share in the 2016 presidential election.

We extend Baccini and Weymouth's analysis by changing the quantity of interest from **gross** manufacturing job losses to **net** manufacturing job losses. For example, in Baccini and Weymouth's model, if a county lost 400 manufacturing jobs from 2012-2015 and also gained 400 manufacturing jobs over the same period, they would count 400 overall layoffs. Using our measure of *net* manufacturing job losses, we would consider this example a 0 net change in manufacturing employment. Given that job destruction and creation is a natural dynamic within the economy (i.e. seasonal employment, creative destruction), we think that *net* job losses is a more meaningful measure.


Using *net* manufacturing job losses as our outcome, we replicate Baccini and Weymouth's main model, which uses 2012-2015 manufacturing (gross) job losses to explain the change in Democratic vote share in 2016. Using their specifications, we find totally opposite results - that a *net* increase in white manufacturing jobs *increased* Democratic vote share, while a *net* increase in non-white manufacturing jobs *decreased* Democratic vote share. 

However, we don't think this is capturing the important dynamic at play. From 2012 to 2015, the national economy experienced a net increase in manufacturing jobs following the 2008 recession (See Figure 1). During this time of recovery, counties that experienced the most pronounced manufacturing job losses in prior years were also likely to experience the most pronounced recovery. Because of this v-shaped recovery, focusing only on 2012-2015 job losses/gains paints a distorted picture. 
