---
title: "Brother, Can You Spare a Manufacturing Job?  How Voters React to Deindustrialization"
short: ""
journal: "" # AER, AEJ, PP, JEL
month: "`r format(Sys.Date(), '%m')`"
year: "`r format(Sys.Date(), '%Y')`"
vol: 1
issue: 1
author:
  - name: Catherine Darin
    firstname: Catherine
    surname: Darin
    email: cdarin@hks.harvard.edu
    affiliation: Harvard University
  - name: Zagreb Mukerjee
    firstname: Zagreb
    surname: Mukerjee
    email: zagrebmukerjee@fas.harvard.edu
    affiliation: Harvard University
acknowledgements: 
abstract: |
  What led to Donald Trump's surprising 2016 election victory? This paper examines the potential contribution of deindustrialization. Counties differ by exposure to manufacturing, which we use in an instrumental-variable approach to identify the effect of manufacturing job loss on change in Democratic vote share. We find that Democratic vote share falls in counties with high manufacturing job loss since 2004. Disaggregating this result by race shows that the Democratic vote share fell where layoffs affected white populations, and rose where layoffs affected nonwhites. This suggests a racial component to how voters process economic hardship.
output: rticles::aea_article
---

```{r}
library(tidyverse)
library(stargazer)
library(sandwich)
library(lmtest)
library(knitr)
library(kableExtra)
library(readxl)
library(scales)
library(tigris)


#knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
#knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```


\section{Introduction}

We replicate Baccini and Wemouth (2021), which analyzes the effect of gross manufacturing job losses from 2012 to 2015 on the change in Democratic vote share in the 2016 presidential election.

We extend Baccini and Weymouth's analysis by changing the quantity of interest from **gross** manufacturing job losses to **net** manufacturing job losses. For example, in Baccini and Weymouth's model, if a county lost 400 manufacturing jobs from 2012-2015 and also gained 400 manufacturing jobs over the same period, they would count 400 overall layoffs. Using our measure of *net* manufacturing job losses, we would consider this example a 0 net change in manufacturing employment. Given that job destruction and creation is a natural dynamic within the economy (i.e. seasonal employment, creative destruction), we think that *net* job losses is a more meaningful measure.


Using *net* manufacturing job losses as our outcome, we replicate Baccini and Weymouth's main model, which uses 2012-2015 manufacturing (gross) job losses to explain the change in Democratic vote share in 2016. Using their specifications, we find totally opposite results - that a *net* increase in white manufacturing jobs *increased* Democratic vote share, while a *net* increase in non-white manufacturing jobs *decreased* Democratic vote share. 

However, we don't think this is capturing the important dynamic at play. From 2012 to 2015, the national economy experienced a net increase in manufacturing jobs following the 2008 recession (See Figure 1). During this time of recovery, counties that experienced the most pronounced manufacturing job losses in prior years were also likely to experience the most pronounced recovery. Because of this v-shaped recovery, focusing only on 2012-2015 job losses/gains paints a distorted picture. 

\section{Data and Methods}

\subsection{Data}

Following \cite{BW}, our unit of analysis is the county. This allows us to capture not only the direct effects of deindustrialization on laid-off manufacturing workers, but also on the local economy. The primary outcome variable is the county's change in Democratic vote share between 2012 and 2016. We obtain this from XXXXXXXXX


We want to measure the causal relationship between deindustrialization and the change in vote share. As a measure of deindustrialization, we use the destruction of manufacturing jobs, as a share of the total employment in each county.  





If we expand our measure of net manufacturing job losses to include the 2004 to 2011 period - which covers most of the period when the U.S. manufacturing economy was hit most intensely (See Figure 1) -- we get a result that corroborates the core intuition of Baccini and Weymouth (See Table 4). That is, we find that net white manufacturing job losses decreased Democratic vote share, while net non-white manufacturing job losses increased Democratic vote share.

It is important to highlight the substantive importance of the *timing* of manufacturing layoffs on political outcomes. Whereas Baccini and Weymouth's analysis suggests that economic changes lead to immediate political consequences, our analysis shows that economic changes can have lagged and variable effects on political outcomes. The mechanisms of these lagged effects merit further study.

[Note: to demonstrate our point about **variable** effects, In our next iteration of the analysis, we will show that manufacturing job losses had little explanatory effect on changes in Democratic vote share in other elections (2012 and 2020).]


Sample figure:



American Economic Review Pointers:

\begin{itemize}
\item Do not use an "Introduction" heading. Begin your introductory material
before the first section heading.

\item Avoid style markup (except sparingly for emphasis).

\item Avoid using explicit vertical or horizontal space.

\item Captions are short and go below figures but above tables.

\item The tablenotes or figurenotes environments may be used below tables
or figures, respectively, as demonstrated below.

\item If you have difficulties with the mathtime package, adjust the package
options appropriately for your platform. If you can't get it to work, just
remove the package or see our technical support document online (please
refer to the author instructions).

\item If you are using an appendix, it goes last, after the bibliography.
Use regular section headings to make the appendix headings.

\item If you are not using an appendix, you may delete the appendix command
and sample appendix section heading.

\item Either the natbib package or the harvard package may be used with bibtex.
To include one of these packages, uncomment the appropriate usepackage command
above. Note: you can't use both packages at once or compile-time errors will result.

\end{itemize}

\section{First Section in Body}

Sample figure:


\begin{figure}

\caption{Caption for figure below.}
\begin{figurenotes}
Figure notes without optional leadin.
\end{figurenotes}
\begin{figurenotes}[Source]
Figure notes with optional leadin (Source, in this case).
\end{figurenotes}
\end{figure}

Sample table:

\begin{table}
\caption{Caption for table above.}

\begin{tabular}{lll}
& Heading 1 & Heading 2 \\
Row 1 & 1 & 2 \\
Row 2 & 3 & 4%
\end{tabular}
\begin{tablenotes}
Table notes environment without optional leadin.
\end{tablenotes}
\begin{tablenotes}[Source]
Table notes environment with optional leadin (Source, in this case).
\end{tablenotes}
\end{table}

References here (manual or bibTeX). If you are using bibTeX, add your bib file
name in place of BibFile in the bibliography command.
% Remove or comment out the next two lines if you are not using bibtex.
\bibliographystyle{aea}
\bibliography{references}

% The appendix command is issued once, prior to all appendices, if any.
\appendix

\section{Mathematical Appendix}
